### PR TITLE
Use rclcpp::Clock::wait_until_started

### PR DESCRIPTION
**Pull request by sloretz**
part of #276 
Draft for now as this requires a new rolling release of rclcpp that includes https://github.com/ros2/rclcpp/pull/2040

@svwilliams for visibility

### CODE REVIEW

**Comment by sloretz** [comment]
Release of rclcpp made: https://github.com/ros/rosdistro/pull/35711

**Comment by sloretz** [comment]
@ros-pull-request-builder retest this please

**Comment by sloretz** [comment]
Self review LGTM

Test failures are only linters in packages that haven't been linted yet

```
colcon test-result
build/fuse_models/Testing/20230127-1831/Test.xml: 12 tests, 0 errors, 4 failures, 0 skipped
build/fuse_models/test_results/fuse_models/copyright.xunit.xml: 48 tests, 0 errors, 2 failures, 0 skipped
build/fuse_models/test_results/fuse_models/cpplint.xunit.xml: 512 tests, 0 errors, 508 failures, 0 skipped
build/fuse_models/test_results/fuse_models/uncrustify.xunit.xml: 48 tests, 0 errors, 48 failures, 0 skipped
build/fuse_models/test_results/fuse_models/xmllint.xunit.xml: 2 tests, 0 errors, 1 failure, 0 skipped
build/fuse_optimizers/Testing/20230127-1831/Test.xml: 11 tests, 0 errors, 2 failures, 0 skipped
build/fuse_optimizers/test_results/fuse_optimizers/cpplint.xunit.xml: 266 tests, 0 errors, 266 failures, 0 skipped
build/fuse_optimizers/test_results/fuse_optimizers/uncrustify.xunit.xml: 17 tests, 0 errors, 17 failures, 0 skipped
build/fuse_tutorials/Testing/20230127-1831/Test.xml: 8 tests, 0 errors, 4 failures, 0 skipped
build/fuse_tutorials/test_results/fuse_tutorials/cpplint.xunit.xml: 94 tests, 0 errors, 94 failures, 0 skipped
build/fuse_tutorials/test_results/fuse_tutorials/flake8.xunit.xml: 6 tests, 0 errors, 6 failures, 0 skipped
build/fuse_tutorials/test_results/fuse_tutorials/uncrustify.xunit.xml: 8 tests, 0 errors, 8 failures, 0 skipped
build/fuse_tutorials/test_results/fuse_tutorials/xmllint.xunit.xml: 2 tests, 0 errors, 1 failure, 0 skipped
```

**Review by methylDragon — APPROVED** [review]

**Comment by methylDragon** [comment]
I'm not sure why the RPr job is failing to find tf2_2d

It's in rosdistro https://github.com/ros/rosdistro/blob/dfb1574b597625fd0dcbe87b5d48a2a93c65eaf9/rolling/distribution.yaml#L5729

**Comment by sloretz** [comment]
The PR job requires tf2_2d to be released into Rolling. Until that happens
we'll have to test locally.

**Pull request merged**
